#!/bin/sh
# OpenWRT uci defaults script
# For generating custom firmwares at https://firmware-selector.openwrt.org
# Current version 25.12.0-rc5 working with devices 8mb rom & 64mb ram
#
# Remove these apps from the default app list
# odhcp6c odhcpd-ipv6only ppp ppp-mod-pppoe
#
# Add these apps
# coreutils-base64 kmod-zram nano luci-app-attendedsysupgrade
# uboot-envtools luci-app-travelmate luci-app-https-dns-proxy
#
# Add if rom > 8mb
# luci-app-adblock-fast gawk grep sed coreutils-sort
#

echo "Starting custom configuration"

# Define variables
model="$(cat /tmp/sysinfo/model | cut -d' ' -f2)"
ip_addr='192.168.10.1'
ssid0=Cheese
ssid1=Pickle
pass=sandwich
uplink_ssid_2g=Custard uplink_pass_2g=pineapple
uplink_ssid_5g=Rhubarb uplink_pass_5g=pineapple
uplink_enc=psk2+ccmp

echo "Setting root password to $pass"
echo -e "$pass\n$pass\n"|passwd >/dev/null 2>&1

echo "Set ssh keys"
cat <<EOF>/etc/dropbear/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC1XUUcJsFN6qAeCyvEiSjUF0nCB8GGBIRXNiBxs+YxW5dZrpb5rAmpnduL95qEX6egVRiwmsybI5nNMLSp9uaGk1rxh0Z9111aqGL8piLO50pNZW5vm6yiU1AJ1NdFq/Hi0iKqeq0U+rAptmPeZQlumspZBDiuQHJdblgeceAsYIgCvRVhQlU6Jh8+wQWm5yIm4xEbsF96k9YVcTI2yXyRbhRQVAgZIVy2u1P6hbNnZ2mB9/TX63M1OmmowSzvSH4oHI4eb9HHmq5tPyeRejp08OkN5fhPYYnl50fYJfYMuG0Cv3EefrCGKDGqzyf0KPytVAc3X/NUwRGl4fYMqRV9uKO6N9cUFN85a15O6ILf4ohik+0B4zjkdiI9rO9Ezz6bBkxePSgEPu/kAl3J/ClTMig6gwMONZAKknwQ5LZqSSzBKA8QVmaF4jeO3YWRD/Xq4G/hJGd42otHTVgpTC5XxlAHxM8T1TRqReviH3qXaB20hBwQp3ykMy80C3bW+qM7gYYJJm5No1uOTmk0nkYnvSVg3UaAiMIt6pRLgnjzM+jW6fHP7lMMSO/R0USEDtPrEqCiRdKp/uSXGsLsrDe8a6EZ5a4HaQCAYLn6N66FFCiQ7y8SFRRZ9FMAf0zI9tS7S0qvZmk5/oWvwboXb4i74Ml9UsHdx/YxkB78kxr2Ww== IG-88
EOF
cat << EOF | base64 -d >/etc/dropbear/dropbear_rsa_key
AAAAB3NzaC1yc2EAAAADAQABAAABAQCR7E0LqNiQ//potwSbs5dEQDERIzow2DHgpBkH7ZaL+4Ee
SP65Ix+ACeUY0TcKlBhsIOL0piSQop6eiXi+cSNvjo6PCs0nVXpJKVcSmof060uO/an+SpAhz3N6
RbzYX8JII6duMA9YEVymvOdVHQd4dGDUygc3ZyYplXJlUUGqtswoXMZ28Hvtj3X4ANnJWaum4+0q
YzjP9AwpI6bD+hEZm0mu0uysixmOOP7+reoBYz/cdlInrvvh+QeNk5NmDcBazajDLaQ3fv2RVqaY
cIo9J+YYNEoGu2gSvZvwLM2d1ZftQxO2B1XZyhT7YzCH3vA4WxRhswludzDex5wP0OQDAAABAD4m
f/YsVvkDHZtGAB900UOPd5aOA3XUTwIXwlV/GvTKDQdiHaOq0vrMvBfi2+eUhgZfx2pd7QrxSE/L
y3KJa4dTF2LTPee331qT0fMpgCiPouHnJmUZSuQroEp+s10RBAWHsgMbUx22X1jg8kJtF8Z1Atz+
oy40r6tcbJm8jxRvGN7PyTfVzN9lRmpx7iBKEvdgDMcf1wmD0NxQdfjPjcdNytN2aN9KIZLxoayw
Wp0IX2sznURi5uDXy+/0ykdQF9wHLZcAW/+8yFa0vndVLa4tAB0UcAxjFNQzdskF3oKXUyo3S24n
cdfL5HjBVQDYKmrQo7GCZRbSCZPhbEkjENEAAACBAJ3AmS0fF9CTJdsLvpfqIAUE6hLuCiwwXpTH
TiSf/rUWRrm9rN7DAtOVLhCWF49SMBwg2Eb2iOxn/9E5vCkkTNRb4pfkUgQXoEWvHoam3wxfIWQ7
VdXwn7hfiZBPRHmIhTxM3IHZyi49b6SDqBNivF3UwspYNqFi2Y18zg8agK0rAAAAgQDszbA/RlaM
ghPIB7lOL+UD62uHrsqgOVDASLhLg3NqjQhwWCZj/1By1EgzDZ3McTqjOk9lIqy67Zcuf1f8coFO
ydo4vJzPldov29zb60L+ckiFIIVe9Qj5i4/g2VCE8aqWgsg6xjEtTc/uW1/4nSsNjSP95SXzplXZ
sju6xfCoiQ==
EOF
cat <<EOF | base64 -d >/etc/dropbear/dropbear_ed25519_host_key
AAAAC3NzaC1lZDI1NTE5AAAAQPOPuYnWDCIRVHdH+FWuyl4pGuKqFNPWSdp1qqRINS6R1K9QDB8r
MI11GrgXM1Y5D/5bTVhGUNLWA1IEEsrC/Wg=
EOF

echo "Configure domain name resolution"
rm /etc/resolv.conf; cat /tmp/resolv.conf>/etc/resolv.conf
echo -e "nameserver 208.67.220.220\nnameserver 208.67.220.220\n">>/etc/resolv.conf
uci del dhcp.@dnsmasq[0].noresolv
uci set dhcp.@dnsmasq[0].resolvfile='/etc/resolv.conf'
uci -q commit dhcp

echo "Configure system settings"
uci set system.@system[0].hostname="$model"
uci set system.@system[0].zram_size_mb='32'
uci set system.@system[0].zram_comp_algo='zstd'
uci set system.@system[0].zonename='Europe/London'
uci set system.@system[0].timezone='GMT0BST,M3.5.0/1,M10.5.0'
uci set system.@system[0].clock_hourcycle='h23'
uci -q commit system

echo "Configure dns over https"
uci set https-dns-proxy.@https-dns-proxy[0].resolver_url='https://dns.quad9.net/dns-query'
uci set https-dns-proxy.@https-dns-proxy[1].resolver_url='https://cloudflare-dns.com/dns-query'
uci -q commit https-dns-proxy

echo "Configure upgrade settings"
uci set attendedsysupgrade.client.login_check_for_upgrades='0'
uci set attendedsysupgrade.client.advanced_mode='1'
uci commit attendedsysupgrade

echo "Config ethernet"
uci set network.lan.ipaddr="$ip_addr/24"
uci set network.globals.packet_steering='1'
uci set network.wwan=interface
uci set network.wwan.proto='dhcp'
[ "$(uci show network|grep wan6)" = "1" ] && uci del network.wan6
uci commit network
service network restart

echo "Configure firewall & remove ipv6 rules"
uci del firewall.@zone[1].network
uci add_list firewall.@zone[1].network='wan'
uci add_list firewall.@zone[1].network='wwan'
for r in "$(uci show firewall|grep ipv6|cut -d'.' -f1-2)"; do uci del "$r"; done
uci -q commit firewall

echo "Configure wifi settings"
for r in $(uci show wireless|grep wifi-device|sed -e 's#wireless.radio\(.\).*#\1#g')
do
    if [ $(uci get wireless.radio$r.band) = "5g" ]; then
        uci set wireless.radio$r.channel="36"
        uci set wireless.radio$r.htmode='VHT80'
    fi
    if [ $(uci get wireless.radio$r.band) = "2g" ]; then
        uci set wireless.radio$r.channel="6"
        uci set wireless.radio$r.htmode='HT40'
    fi
    uci set wireless.radio$r.country="GB"
    uci set wireless.default_radio$r.ssid=$(eval "echo \$ssid$r")
    uci set wireless.default_radio$r.encryption="psk2+ccmp"
    uci set wireless.default_radio$r.key="$pass"
    uci set wireless.default_radio$r.disabled="0"
    uci set wireless.radio$r.cell_density='0'
    uci -q commit wireless
    wifi reload
done

echo "Configure Travelmate"
if [ "$(uci get wireless.radio0.band)" = '5g' ]; then
    uplink_ssid0=$uplink_ssid_5g; uplink_ssid1=$uplink_ssid_2g
    uplink_pass0=$uplink_pass_5g; uplink_pass1=$uplink_pass_2g
fi
if [ "$(uci get wireless.radio0.band)" = '2g' ]; then
    uplink_ssid0=$uplink_ssid_2g; uplink_ssid1=uplink_ssid_5g
    uplink_pass0=$uplink_pass_2g; uplink_pass1=$uplink_pass_5g
fi
uci set travelmate.global.trm_enabled='1'
uci set travelmate.global.trm_iface='wwan'
uci add travelmate uplink
uci set travelmate.@uplink[-1].enabled='1'
for r in $(uci show wireless|grep wifi-device|sed -e 's#wireless.radio\(.\).*#\1#g')
do
    uci set travelmate.@uplink[-1].device="radio$r"
    uci set travelmate.@uplink[-1].ssid=$(eval "echo \$uplink_ssid$r")
    uci set travelmate.@uplink[-1].con_start_expiry='0'
    uci set travelmate.@uplink[-1].con_end_expiry='0'
    uci -q commit travelmate

    uci set wireless.trm_uplink$r=wifi-iface
    uci set wireless.trm_uplink$r.device=radio$r
    uci set wireless.trm_uplink$r.mode='sta'
    uci set wireless.trm_uplink$r.network='wwan'
    uci set wireless.trm_uplink$r.ssid=$(eval "echo \$uplink_ssid$r")
    uci set wireless.trm_uplink$r.encryption="$uplink_enc"
    uci set wireless.trm_uplink$r.key=$(eval "echo \$uplink_pass$r")
    uci set wireless.trm_uplink$r.disabled='0'
    uci -q commit wireless
done

# Configure profile
[ $(grep -c 'alias nano' /etc/profile) = '0' ] && echo "alias nano='nano -l -c'">>/etc/profile

echo "Configuration complete"
